lib/takso_web/router.ex
defmodule TaksoWeb.Router do
  use TaksoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    #plug Takso.Authentication, repo: Takso.Repo
  end

  pipeline :browser_auth do
    plug Takso.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaksoWeb do
    pipe_through [:browser]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", TaksoWeb do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index
  end

  scope "/", TaksoWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/users", UserController
    get "/bookings/summary", BookingController, :summary
    resources "/bookings", BookingController
    resources "/allocations", AllocationController do
      get "/accept", AllocationController, :accept, as: :accept
      get "/reject", AllocationController, :reject, as: :reject
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaksoWeb do
  #   pipe_through :api
  # end
end

lib/takso/sales/allocation.ex
defmodule Takso.Sales.Allocation do
  use Ecto.Schema
  import Ecto.Changeset

  schema "allocations" do
    field :status, :string
    belongs_to :booking, Takso.Sales.Booking
    belongs_to :taxi, Takso.Sales.Taxi

    timestamps()
  end

  @doc false
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:status, :booking_id, :taxi_id])
    |> validate_required([:status])
  end

end

lib/takso_web/controllers/allocation_controller.ex
defmodule TaksoWeb.AllocationController do
  use TaksoWeb, :controller
  import Ecto.Query, only: [from: 2]

  alias Takso.{Repo, Authentication}
  alias Ecto.{Changeset, Multi}
  alias Takso.Sales.{Taxi, Booking, Allocation}


  def index(conn, _params) do
    allocs = Repo.all(Allocation) |> Repo.preload([:taxi, :booking])
    render(conn, "index.html", allocs: allocs)
  end

  def accept(conn, %{"id" => id}) do
    user = Authentication.load_current_user(conn)
    allocation = Repo.get!(Allocation, id) |> Repo.preload([:taxi, :booking])
    booking = allocation.booking |> Repo.preload([:user])
    taxi = allocation.taxi

    # IO.puts "burdadi"
    IO.inspect user

    if allocation.taxi.username == user.username do
      Multi.new
      |> Multi.update(:allocation, Allocation.changeset(allocation, %{}) |> Changeset.put_change(:status, "allocated"))
      |> Multi.update(:taxi, Taxi.changeset(taxi, %{}) |> Changeset.put_change(:status, "busy"))
      |> Multi.update(:booking, Booking.changeset(booking, %{}) |> Changeset.put_change(:status, "accepted"))
      |> Repo.transaction()

      conn
      |> put_flash(:info, "You have accepted the booking")
      |> redirect(to: allocation_path(conn, :index))
    else
      conn
      |> put_flash(:error, "You are not permitted to accept this allocation")
      |> redirect(to: allocation_path(conn, :index))
    end


  end

  def reject(conn, %{"id" => id}) do
    render(conn, id)
  end
end

lib/takso_web/views/allocation_view.ex
defmodule TaksoWeb.AllocationView do
  use TaksoWeb, :view
end
defmodule TaksoWeb.AllocationView do
  use TaksoWeb, :view
end

lib/takso_web/templates/allocation/index.html.eex
<h2>Listing allocations</h2>

<table class="table">
  <thead>
    <tr>
      <th>Status</th>
      <th>Booking</th>
      <th>Taxi</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for alloc <- @allocs do %>
        <tr>
        <td><%= alloc.status %></td>
        <td><%= alloc.booking_id %></td>
        <td><%= alloc.taxi_id %></td>

        <td class="text-right">
            <span><%= link "Accept", to: allocation_accept_path(@conn, :accept, alloc), id: "accept"<>to_string(alloc.id), class: "btn btn-default btn-xs" %></span>
            <span><%= link "Reject", to: allocation_reject_path(@conn, :reject, alloc), id: "reject"<>to_string(alloc.id), class: "btn btn-default btn-xs" %></span>
        </td>
        </tr>
    <% end %>
  </tbody>
</table>

<%# <span><%= link "New user", to: user_path(@conn, :new) %>
<%# </span> %>